### ISSUE TITLE
[BUG] SC Inspector fails on functions with dynamically sized array params.

### ISSUE THREAD

**Issue by lastperson** [zviadm/celoterminal#222]
**Environment**
Operating System: Windows 10
Celo Terminal Version: 1.9.19

**Describe the bug**
Trying to execute "executeMany" function on the 0x313bc86D3D6e86ba164B2B451cB0D9CfA7943e5c contract produces an error "param.map is not a function".

**To Reproduce**
1. Go to SC Inspector
2. Paste 0x313bc86D3D6e86ba164B2B451cB0D9CfA7943e5c in the Contract address
3. Click WRITE
4. Click executeMany
5. Type "0x313bc86D3D6e86ba164B2B451cB0D9CfA7943e5c,0x313bc86D3D6e86ba164B2B451cB0D9CfA7943e5c" into to() field
6. Type 0,0 into value() field
7. Type 0x12,0x12 into data() field
8. Click EXECUTE

**Expected behavior**
Transaction is sent.

![image](https://user-images.githubusercontent.com/6198746/136454650-ac7dcccd-bfb7-448c-a9ce-86bbda39a61b.png)

**Comment by zviadm** [comment]
Thanks for the report. I think i know what the issue is, all arguments are passed through as strings, but when type is array (`[]`) they need to be passed as array of strings instead to the contract call.

Should have a fix done pretty soon.
