### ISSUE TITLE
[BUG] Celo Terminal does not update

### ISSUE THREAD

**Issue by kopeboy** [zviadm/celoterminal#270]
**Environment**
Operating System: macOS 12.0.1
Celo Terminal Version: 1.11.5

**Describe the bug**
Trying to update Celo Terminal, clicking on the "v1.11.5 → v1.11.13" button at the bottom of the left menu, leads to nothing after 30mins+ of waiting. Refreshing the page with cmd+r removes the loading bar under the clicked button and suggests the app wasn't really updating. 

**To Reproduce**
1. open app
2. Click on "v1.11.5 → v1.11.13" button at the bottom of the left menu
3. See the progress bar animation, wait
4. Nothing happens (app update expected?)

**Expected behavior**
App should update after clicking that button? How should we update otherwise? Thank you

**Comment by zviadm** [comment]
When you click "update" button, it starts downloading the new version. Depending on your internet connection, it can take some time to do so. 

It seems like update is working for others, so it might be some sort of a local issue with internet connection. 

As for other ways to update, you can just download new version from either github or directly from celoterminal.com and install that by replacing the old version and it should all work fine.
