### ISSUE TITLE
wallet mobile app

### ISSUE THREAD

**Issue by dinarpay** [zviadm/celoterminal#273]
Can the wallet be developed?
for mobile app

**Comment by zviadm** [comment]
There are already great mobile apps for Celo, like: https://valoraapp.com/ which has integrations with other mobile web apps that work for Celo. 

Celo Terminal full-fills a specific niche of Desktop first app for users who need more security (like using Ledger HW wallet) and reliability (like connecting to a custom or local client node, controlling app upgrades etc).
