### ISSUE TITLE
Missing EIP-1167 Support: Verified Proxy Contracts are not resolved

### ISSUE THREAD

**Issue by shredding** [zviadm/celoterminal#274]
**Environment**
Operating System: all
Celo Terminal Version: 1.11.15

**Describe the bug**
If one uses a proxy pattern like EIP-1167 celoterminal gives no insights in the actual transaction data.

E.g. this contract was deployed using the `ClonesUpgradeable` lib from openzeppelin: https://explorer.celo.org/address/0x31927663bb737a1eD7655b0684986A836F52E548/read-contract

celoscan and the likes have support for that pattern, but celoterminal hides the transaction data, making the multisig pattern unusable, as there is no insight into what one is actually signing:

![image](https://user-images.githubusercontent.com/930136/172863467-d5d041a8-76dd-462e-ac80-cdc2c1494578.png)

**To Reproduce**
1. Create a multisig wallet
2. Generate a tx to the contract above (e.g. using `approve`)
3. Submit it and review on celo terminal

**Expected behavior**
See insights into the actual transaction data

**Comment by zviadm** [comment]
Yes this is sort of a known issue. Proxy implementation right now only supports Celo Proxy contract, others have to be added manually. 
Unfortunately i think Etherscan/Celoscan code isn't open source so it isn't easy to just take their implementation and port it for Celo Terminal. 

If there are ideas on how to improve overall proxy detection + parsing happy to look at PRs or even implement them later on myself.

**Comment by zviadm** [comment]
Newest version now uses celoscan.xyz as a backup, thus if a proxy contract and its implementations are verified on celoscan, it should also work in CeloTerminal too

**Comment by shredding** [comment]
Thanks so much!
