### ISSUE TITLE
[BUG] Trying to connect using wallet connect v2 gives wallet connect v1 error

### ISSUE THREAD

**Issue by hughlaw** [zviadm/celoterminal#295]
**Environment**
Operating System: macOS 13.3.1
Celo Terminal Version: 1.14.6

**Describe the bug**
Trying to connect to a dapp using wallet connect v2, when copying the wallet connect connection string and pasting it into Celo Terminal, the connection does not connect and gives what seems like a Wallet connect V1 error:

```
Invalid WalletConnect v1 QRCode: Error: Invalid or missing bridge url parameter value
```

The [Celo terminal docs](https://docs.celoterminal.com/guides/using-walletconnect) state: "Celo Terminal supports [WalletConnect v2.0](https://docs.walletconnect.org/v/2.0/) out-of-the box."

**To Reproduce**
1. Go to https://react-app.walletconnect.com/
2. Disable Testnets Only switch
3. Select Celo network
4. Click "connect" button to open wallet connect modal
5. copy connection string
6. open Celo Terminal
7. Select Wallet connect option
8. Paste connection string into "QRCode" field in Celo terminal

Please attach screenshots if you can.

<img width="1428" alt="image" src="https://github.com/zviadm/celoterminal/assets/3457716/74ef2b5c-a0de-4298-a3e1-fbb45165e5e2">

**Expected behavior**
A wallet connect connection should be established

**Comment by bark4mark** [comment]
I get the same error using version 1.14.6 on linux
![image](https://github.com/zviadm/celoterminal/assets/4677277/4fe571d7-93df-4263-b966-de3d12fac0e5)

**Comment by zviadm** [comment]
Hello, thanks for the report. 

The wiki is inaccurate. CeloTerminal doesn't support WalletConnect v2 yet. There is a work in progress diff to get it the v2 protocol to work but as it is right now it only supports WalletConnect v1.

**Comment by zviadm** [comment]
initial support for WalletConnect V2 should be in v1.15.0 beta of CeloTerminal.
This stuff is fairly flaky, so if you do find some issues, feel free to report them as separate bugs.
