### ISSUE TITLE
[BUG] MultiSig creation failed: ENS is not supported on network private

### ISSUE THREAD

**Issue by MysterPAN** [zviadm/celoterminal#305]
**Environment**
Operating System: Win10
Celo Terminal Version: 1.18.2

**Bug description**
I tried to create a new MultiSig using the 'Create MultiSig Account' in the Accounts tab.
I keep getting this error: 'ENS is not supported on network private' and the creation systematically fails, consuming the fee.
I tried swapping the owners' addresses but it does not seem to make a difference.
Looks like this is a known issue in the [Ethereum](https://github.com/NomicFoundation/hardhat/issues/1289) [community ](https://github.com/web3/web3.js/issues/3787) but I cannot find any trace of it in Celo dapps.

![image](https://github.com/zviadm/celoterminal/assets/100414614/b9a0a651-608d-4b52-9910-26c99ee2d196)

The tx initiating the smart contract goes through (e.g. [here](https://celoscan.io/address/0x52c4cbbd492f4285ded48927b88c7efc0cec1055)) but when I try to add the multisig by importing the contract's address, I run into an error code stating the execution was reverted: 'execution reverted: No Implementation set'

Can someone look into this and give a noob some help?

**Comment by zviadm** [comment]
The "ENS is not supported on network private" is just a red-herring. Have pushed a fix that will make those errors go away.

You must be getting some other error in creation. I just tried it out and it is working fine from my account. Is there anything special about the account you are using to create the multisig account from?

**Comment by MysterPAN** [comment]
Just updated the app. It works great. No more errors and creation successful.
Thank you for the patch 👍 

> Is there anything special about the account you are using to create the multisig account from?

Nothing particular really. I ended up creating a multisig on Safe.global and it went smoothly.
