### ISSUE TITLE
[BUG] Connecting Celo Terminal (local) wallet to app.stcelo.xyz via WalletConnect doesn't work

### ISSUE THREAD

**Issue by 0xarthurxyz** [zviadm/celoterminal#309]
**Environment**
Operating System: macOS 13.5.1 
Celo Terminal Version: [e.g. 1.0.16, version is located at the bottom of the app menu]

**Describe the bug**
Cannot connect Celo Terminal (local) wallet to stCelo app via WalletConnect.

**To Reproduce**
1. Go to app.stcelo.xyz
2. Click on connect > walletconnect > "open"
3. Copy the the URI
4. Go to Celo Terminal > WalletConnect
5. Paste URI
6. Click connect
7. See error ("Not initialized. subscription")

**See attached video:**

https://github.com/zviadm/celoterminal/assets/46296830/069537cd-b493-4ef5-bf7f-a807bc7ce12b

Attempted debugging:

- To debug, I attempted to follow guidance here: https://docs.celoterminal.com/guides/using-walletconnect
- Test: I’m able to connect Safe ([app.safe.global](https://app.safe.global/)) with stCelo (app.stcelo.xyz) over WalletConnect.

**Expected behavior**
When pasting a WalletConnect URI, Celo Terminal should connect.

**Comment by zviadm** [comment]
Yes, this is a known issue. If you restart Celo Terminal, it will work fine again. 
There is some issues with WalletConnect client going stale when Celo Terminal is running in background for too long. 

As a workaround for now, you can just restart Celo Terminal and it will work again.

**Comment by 0xarthurxyz** [comment]
Thanks for the speedy response @zviadm. 
Restarting Celo Terminal does indeed fix the issue above ✅
