### ISSUE TITLE
[BUG] Not able to connect on autofarm using wallet connect (old version and new versions)

### ISSUE THREAD

**Issue by loiu92** [zviadm/celoterminal#313]
**Environment**
Operating System: Windows 11, Linux

Celo Terminal Version: 1.15.0, 1.11.1, 1.18.5

**Describe the bug**
I can't connect to autofarm using wallet connect and celo terminal. I used it one year ago on a macbook and it was working
I tried with ledger and also with wallet using private keys directly.

**To Reproduce**
1. Go to https://autofarm.network/
2. Click on Wallet
3. Login with WalletConnect

**Expected behavior**
I expect to login on autofarm

**Comment by zviadm** [comment]
Looks like autofarm is using WalletConnect v1 which has now been completely deprecated. AutoFarm will have to upgrade to WalletConnect v2 for any WalletConnect stuff to work.
