### ISSUE TITLE
[BUG] WalletConnect fails to sign transactions

### ISSUE THREAD

**Issue by martinvol** [zviadm/celoterminal#349]
**Environment**
Operating System: [e.g. macOS 14.5]
Celo Terminal Version: 2.0.6

**Describe the bug**
When trying to sign a transaction with wallet connect with a wallet in a ledger, the following error prompts: `Gas must be provided to sign a transaction`.

Signing messages under the same conditions do work.

**To Reproduce**
1. Go to any dApp that supports Wallet Connect (like [stCelo](https://app.stcelo.xyz/stake)) and get the QR/URL
2. Connect that URL with Celo Terminal
3. Try to sign a tx in the app.
4. Celo terminal promts, but then the error prompts. The frontends usually also acknowledge an error.

**Expected behavior**
Transaction should be signed and then broadcasted by frontends.

**Comment by zviadm** [comment]
if TXs work with regular wallets but fail with Ledger accounts, it is most likely related to issues here: https://github.com/zviadm/celoterminal/issues/344
